name: Publish Docker image upon new release

on:
  release:
    types: ["published"]

jobs:
  build:
    uses: ukasyah-dev/actions/.github/workflows/build-docker-go.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit
